[package]
name = "pun"
version = "0.0.1"
edition = "2021"
[ dependencies ]
rand = "^0.8"
egui = "0.19.0"
eframe = "0.19.0"
lib = { path = "../../ost/lib" }
[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
